### ISSUE TITLE
Do not run afterInstall when running `yarn version`

### ISSUE THREAD

**Issue by leabaertschi** [mhassan1/yarn-plugin-after-install#15]
Hi,

first of all thanks a lot for this plugin, this saved me a lot of trouble.

I noticed that `yarn version` is running a `yarn install` and therefore it also runs the `afterInstall` hook. I saw that you already have an exception for when the dependency tree is being updated. Could you add another one that the hook is not run when executing `yarn version`? Or do you see a reason why this could be dangerous?

**Comment by mhassan1** [comment]
I'd rather not add too many assumptions to this library. It's possible that some users will prefer to have the hook run on `yarn version`, since an `install` seems to be happening.

If there's a case where you want to skip the `afterInstall` hook, you can add logic to your script that short-circuits it; for example, you could check an existing or new environment variable to detect whether this is a case where you want to exit early, and exit early.
