### ISSUE TITLE
afterInstall running on projects excluded from the workspace

### ISSUE THREAD

**Issue by michaelfaith** [mhassan1/yarn-plugin-after-install#6]
I have multiple projects in a monorepo that's using yarn 3.  All of the projects except one are connected to the yarn workspace declared at the root.  But one of the projects can't use pnp, and so we've excluded it from the workspace and it has its own `yarn.lock` and `.yarn` folder.  All of this works fine, except that the afterInstall declared in the root `.yarnrc.yml` (part of the workspace) is executing when the child project (excluded from the workspace) runs install.  AfterInstall shouldn't run on projects that are excluded from the workspace.

File structure:
/
-| /projects
---| /project-a
---| /project-b
---| /project-c

root package workspaces
```
"workspaces": [
    "projects/!(project-b)"
  ],
```

And the root `.yarnrc.yml` has an `afterInstall` script.  When `project-b` installs, it's still running the `afterInstall` that the root declares, even though that project's `.yarnrc.yml` doens't have one.

**Comment by mhassan1** [comment]
Unfortunately, this is just how Yarn Berry works. The `.yarnrc.yml` files get merged together by traversing up the directory tree, regardless of whether they are part of the workspace, or not ([link](https://github.com/yarnpkg/berry/blob/4a097fa80c0fc42e3d5eb51c597bf7304e981111/packages/yarnpkg-core/sources/Configuration.ts#L1151)).

The workaround would be to specify `afterInstall: echo noop` or something in the `yarnrc.yml` of `project-b`, since the directory traversal will use the closest configuration value it encounters.

**Comment by michaelfaith** [comment]
Ah, I see.  Well I appreciate the detail on that.  I'll give your workaround suggestion a shot.
